export const ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  AFFILIATE: 'AFFILIATE',
  FREE_USER: 'FREE_USER',
  PRO_USER: 'PRO_USER',
} as const;

export const PERMISSIONS = {
  READ: 'READ',
  WRITE: 'WRITE',
  DELETE: 'DELETE',
  MANAGE_USERS: 'MANAGE_USERS',
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [PERMISSIONS.READ, PERMISSIONS.WRITE, PERMISSIONS.DELETE, PERMISSIONS.MANAGE_USERS],
  [ROLES.MODERATOR]: [PERMISSIONS.READ, PERMISSIONS.WRITE, PERMISSIONS.DELETE],
  [ROLES.AFFILIATE]: [PERMISSIONS.READ],
  [ROLES.PRO_USER]: [PERMISSIONS.READ],
  [ROLES.FREE_USER]: [PERMISSIONS.READ],
};
